googleAnalytics = "G-NWBJCFBR3S"

baseURL = 'https://www.bhaswanth.in/'
languageCode = 'en-us'
title = 'Notes'

# Book configuration
disablePathToLower = true
#enableGitInfo = true

[markup.tableOfContents]
  startLevel = 1

[menu]
  [[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 1

[params]
    BookTheme = 'dark'
    BookToC = true
    BookFavicon = 'favicon.ico'
    #BookLogo = 'logo.svg'
    #BookMenuBundle = '/menu'
    #BookRepo = 'https://github.com/bhaswanthc/notes
    BookDateFormat = 'January 2, 2006'
    BookSearch = true
    #BookComments = true
    #BookPortableLinks = true
    #BookServiceWorker = true
    BookSection = 'docs'